[package]
name = "messages"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
rsiot = { workspace = true }
serde = { workspace = true }
