!include <C4/C4_Container>
!include <tupadr3/devicons/redis>
!include <tupadr3/devicons/rust>
!include <tupadr3/devicons/postgresql>

title smarthome-rs

Container(webapp, "webapp", "Leptos, WASM", "", $sprite="rust")
Container(api, "api", "axum", "", $sprite="rust")
Container(websocket, "websocket", $sprite="rust")
Container(redis, "redis", "Hash, PubSub", "", $sprite="redis")
Container(db_saver, "db-saver", "sqlx", "", $sprite="rust")
Container(db, "db", "PostgreSQL, TimeseriesDB", "", $sprite="postgresql")
Container(grafana, "grafana", "", "Отображение графиков")
Container(loki, "loki", "", "Логгирование")
Container(plc, "plc", "Siemens", "")
Container(deconz_ws, "deconz-ws", "websocket", $sprite="rust")
Container(deconz_hub, "Deconz Hub")
Container(yeelight, "Yeelight", $sprite="rust")

Rel(webapp, api, "http query")
Rel_Back(webapp, websocket, "push")
Rel_Back(websocket, redis, "subscription")
Rel(api, redis, "get hash")
Rel_Neighbor(redis, db_saver, "subscription")
Rel_Neighbor(db_saver, db, "save")
Rel_Back(grafana, db, "SQL")
Rel_Back(grafana, loki, "LogQL")
Rel_Back(redis, deconz_ws, "publication")
Rel_Back(deconz_ws, deconz_hub, "push")
Rel(redis, yeelight, "pub/sub")