[package]
name = "deconz-ws"
version = "0.0.0"
edition = "2021"


[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

rsiot-component-core = { workspace = true }
rsiot-extra-components = { workspace = true }
rsiot-messages-core = { workspace = true }
rsiot-websocket-client = { workspace = true }

[dev-dependencies]
