[package]
name = "deconz-ws"
version = "0.0.0"
edition = "2021"


[dependencies]
chrono = { workspace = true }
rsiot = { workspace = true, features = [
    "redis-publisher",
    "redis-subscriber",
    "websocket-client",
] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
openssl = { workspace = true }

messages = { workspace = true }
env_vars = { workspace = true }
logging = { workspace = true }

[dev-dependencies]
