[package]
name = "websocket-server"
version = "0.0.1"
edition.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
rsiot = { workspace = true }

env_vars = { workspace = true }
logging = { workspace = true }
messages = { workspace = true }
